# Development version with hot reload
version: '3.8'

services:
  # Backend API (Development)
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: cars4films-backend-dev
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:./dev.db
      - PORT=3000
      - NODE_ENV=development
      - CORS_ORIGIN=http://localhost:5173
    volumes:
      - ./backend:/app
      - /app/node_modules
      - backend_data:/app/prisma
    networks:
      - cars4films-network
    command: npm run dev
    restart: unless-stopped

  # Frontend React App (Development)
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: cars4films-frontend-dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend-dev
    networks:
      - cars4films-network
    command: npm run dev -- --host 0.0.0.0
    restart: unless-stopped

volumes:
  backend_data:
    driver: local

networks:
  cars4films-network:
    driver: bridge