version: "3.8"

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cars4films-backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:./dev.db
      - PORT=3000
      - NODE_ENV=production
      - CORS_ORIGIN=http://localhost:5173
    volumes:
      - backend_data:/app/prisma
    networks:
      - cars4films-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cars4films-frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:3000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - cars4films-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

volumes:
  backend_data:
    driver: local

networks:
  cars4films-network:
    driver: bridge
